#!/bin/sh
# This scripts prepares the configure script for execution.
# Prior to building configure, it makes sure that at least
# the basic autotools are there and are an acceptable version.

# This is a part of the VegaStrike build system.
# This file is released under the GNU Public license.  A
# copy of this license should be available in the same
# directory as this file.

echo VegaStrike Configuration Preparation Tool
echo Maintained by Brian A. Lloyd 
echo '(balloyd1@users.sourceforge.net)'
echo Please send bug reports or comments about this script
echo to the email above or else visit
echo vegastrike.sourceforge.net for help in using this script

checkversion()
{
  ver_ok=NO
  read t1 t2 t3 t4 t5;
  if (test x$t4 "<" x$ver_needed) then
    ver_ok=NO
  else
    ver_ok=OK
  fi
  while read; do
    true;
  done
  if (test x$ver_ok = xOK) then
    return 0;
  else
    return 1;
  fi
}

# Set these variables only if they are not set in the environment.

if [ "x$ACLOCAL" = "x" ]; then
    ACLOCAL=aclocal
    # Debian systems need a new aclocal.
    aclocal-1.7 --version > /dev/null 2> /dev/null && ACLOCAL=aclocal-1.7
fi

if [ "x$AUTOMAKE" = "x" ]; then
    AUTOMAKE=automake
    # Debian systems need a new automake.
    automake-1.7 --version > /dev/null 2> /dev/null && AUTOMAKE=automake-1.7
fi

if [ "x$AUTOCONF" = "x" ]; then
    AUTOCONF=autoconf
fi

if [ "x$AUTOHEADER" = "x" ]; then
    AUTOHEADER=autoheader
fi



vers_ok=OK
ver_needed=1.5

"$ACLOCAL" --version|checkversion
if (test $? -ne 0) then
  echo "aclocal is not new enough.  Please upgrade to at least version $ver_needed"
  vers_ok=NO
fi

"$AUTOMAKE" --version|checkversion
if (test $? -ne 0) then
  echo "automake is not new enough.  Please upgrade to at least version $ver_needed"
  vers_ok=NO
fi

ver_needed=2.53
"$AUTOHEADER" --version|checkversion
if (test $? -ne 0) then
  echo "autoheader is not new enough.  Please upgrade to at least version $ver_needed"
  vers_ok=NO
fi

"$AUTOCONF" --version|checkversion
if (test $? -ne 0) then
  echo "autoconf is not new enough.  Please upgrade to at least version $ver_needed"
  vers_ok=NO
fi

if (test x$vers_ok = xOK) then
{
if ("$ACLOCAL" -I m4scripts) then
  ( "$AUTOHEADER" -f && "$AUTOCONF" -f && "$AUTOMAKE" -acf && \
    echo "Bootstrap is complete. Run ./configure to configure the build system." ) || \
    echo "An error occurred while running the autotools.  Please correct."
else
  echo "m4scripts directory appears to be missing."
  echo "try running cvs update -P -d"
  echo "in the directory that bootstrap-sh is in."
fi
}
fi
