#!/bin/sh
#====================================
# @file   : clean
# @version: 2020-02-12
# @created: 2020-02-12
# @author : pyramid
# @brief  : cleans VegaStrike build
# @usage  : sh/clean
# @param  : none
#====================================

echo "--------------------------"
echo "--- clean | 2020-02-12 ---"
echo "--------------------------"
echo "!!!warning!!! for strict developer use"
echo "--------------------------"

#----------------------------------
# validate parameters
#----------------------------------

ROOT_DIR=$(pwd)
BUILD_DIR=$ROOT_DIR/build
BIN_DIR=$ROOT_DIR/bin
DATA_DIR=$ROOT_DIR/data
SRC_DIR=$ROOT_DIR/engine

# delete build directory
echo "deleting build directory ($BUILD_DIR)"
rm -r $BUILD_DIR

# delete .pyc files
echo "deleting compiled python files (*.pyc)"
find $DATA_DIR -name "*.pyc" -delete

# delete home vegastrike config
echo "deleting home vegastrike.config"
rm ~/.vegastrike/vegastrike.config
echo "run bin/vssetup to create a new setup"
