set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} /DBOOST_ALL_DYN_LINK /DBOOST_USE_WINAPI_VERSION=0x0A00 /D_WIN32_WINNT=0x0A00 /DWINVER=0x0A00")
set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} /DBOOST_ALL_DYN_LINK /DBOOST_USE_WINAPI_VERSION=0x0A00 /D_WIN32_WINNT=0x0A00 /DWINVER=0x0A00")

if("${PORT}" STREQUAL "opentelemetry-cpp")
    list(APPEND VCPKG_CXX_FLAGS -DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_CXX_EXTENSIONS=OFF -DBUILD_TESTING=OFF -DWITH_OTLP_FILE=ON -DWITH_STL=OFF -DWITH_EXAMPLES=OFF -DCMAKE_MAP_IMPORTED_CONFIG_RELWITHDEBINFO=Debug -DOPENTELEMETRY_BUILD_DLL=OFF -DOPENTELEMETRY_INSTALL=ON)
endif()
