set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS -DBOOST_USE_WINAPI_VERSION=0x0A00 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00)
