set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

IF (PORT STREQUAL "openssl")
    set(VCPKG_CONFIGURE_MAKE_OPTIONS "-DOPENSSL_NO_AUTOLOAD_CONFIG")
ELSEIF (PORT STREQUAL "python3")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
    SET(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_STANDARD_REQUIRED:BOOL=ON -DCMAKE_CXX_EXTENSIONS:BOOL=ON")
ELSE ()
    SET(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_STANDARD_REQUIRED:BOOL=ON -DCMAKE_CXX_EXTENSIONS:BOOL=ON")
ENDIF ()
