set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

IF (PORT STREQUAL "openssl")
    set(VCPKG_CONFIGURE_MAKE_OPTIONS "-DOPENSSL_NO_AUTOLOAD_CONFIG")
ENDIF ()
