#!/usr/bin/env bash
#====================================
# @file   : bootstrap
# @brief  : installs dependencies for building Vega Strike
# @usage  : sudo script/bootstrap 1 (to update all installed packages on the
#           system in the process)
#     or  : sudo script/bootstrap 0 (to skip updating, and just install the
#           new packages that are needed)
# @param  : just one parameter, either a 1 or a 0, to indicate whether or not to
#           UPDATE_ALL_SYSTEM_PACKAGES
#====================================
# Copyright (C) 2020-2025 Roy Falk, Stephen G. Tuggy, Benjamen R. Meyer,
# and other Vega Strike contributors
#
# This file is part of Vega Strike.
#
# Vega Strike is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Vega Strike is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Vega Strike.  If not, see <https://www.gnu.org/licenses/>.

set -e

echo "------------------------------"
echo "--- bootstrap | 2025-11-29 ---"
echo "------------------------------"

platform="$(uname | tr '[:upper:]' '[:lower:]')"

case "$platform" in
    "linux"|"linux-gnu")
        echo "Bootstrapping on Linux..."
        if [ -f ./script/bootstrap-on-linux.sh ] && [ -x ./script/bootstrap-on-linux.sh ]
        then
            ./script/bootstrap-on-linux.sh "$1"
        elif [ -f ./bootstrap-on-linux.sh ] && [ -x ./bootstrap-on-linux.sh ]
        then
            ./bootstrap-on-linux.sh "$1"
        else
            echo "Error locating bootstrap-on-linux.sh"
            exit 3
        fi
        ;;
    "darwin")
        echo "Bootstrapping on macOS X or later..."
        if [ -f ./script/bootstrap-on-macos.sh ] && [ -x ./script/bootstrap-on-macos.sh ]
        then
            ./script/bootstrap-on-macos.sh "$1"
        elif [ -f ./bootstrap-on-macos.sh ] && [ -x ./bootstrap-on-macos.sh ]
        then
            ./bootstrap-on-macos.sh "$1"
        else
            echo "Error locating bootstrap-on-macos.sh"
            exit 3
        fi
        ;;
    *)
        echo "Sorry, unrecognized or unsupported operating system"
        exit 2
        ;;
esac
