#!/bin/bash
#====================================
# @file   : bootstrap
# @brief  : installs dependencies for building Vega Strike
# @usage  : ./script/bootstrap
# @param  : none
#====================================

set -e

echo "------------------------------"
echo "--- bootstrap | 2020-08-17 ---"
echo "------------------------------"

if [ -f /etc/os-release ]
then
    export OS_RELEASE_LOCATION="/etc/os-release"
elif [ -f /usr/lib/os-release ]
then
    export OS_RELEASE_LOCATION="/usr/lib/os-release"
else
    echo "os-release file not found; unable to continue"
    exit 1
fi
export LINUX_ID=$(cat $OS_RELEASE_LOCATION | grep ^ID= | sed 's/^ID=//' | tr -d '"\n')
echo "LINUX_ID = ${LINUX_ID}"
export LINUX_CODENAME=$(cat $OS_RELEASE_LOCATION | grep ^VERSION_CODENAME= | sed 's/^VERSION_CODENAME=//' | tr -d '"\n')
echo "LINUX_CODENAME = ${LINUX_CODENAME}"
export LINUX_VERSION_ID=$(cat $OS_RELEASE_LOCATION | grep ^VERSION_ID= | sed 's/^VERSION_ID=//' | tr -d '"\n')
echo "LINUX_VERSION_ID = ${LINUX_VERSION_ID}"

if [ $LINUX_ID == "debian" ] && [ $LINUX_CODENAME == "buster" ]
then
    sudo apt-get -y install \
                    git \
                    cmake \
                    python-dev \
                    build-essential \
                    automake \
                    autoconf \
                    libpng16-16 \
                    libpng-dev \
                    libpng-tools \
                    libjpeg62-turbo-dev \
                    libexpat1-dev \
                    libgtk2.0-dev \
                    libgtk-3-dev \
                    libopenal-dev \
                    libogg-dev \
                    libvorbis-dev \
                    libgl1-mesa-dev \
                    libsdl1.2-dev \
                    libpostproc-dev \
                    freeglut3-dev \
                    libboost-python1.67-dev \
                    libboost-log1.67-dev \
                    libboost-regex1.67-dev
elif [ $LINUX_ID == "debian" ] && [ $LINUX_CODENAME == "stretch" ]
then
    sudo apt-get -y install \
                    git \
                    cmake \
                    python-dev \
                    build-essential \
                    automake \
                    autoconf \
                    libpng16-16 \
                    libpng-dev \
                    libpng-tools \
                    libjpeg62-turbo-dev \
                    libexpat1-dev \
                    libgtk2.0-dev \
                    libgtk-3-dev \
                    libopenal-dev \
                    libogg-dev \
                    libvorbis-dev \
                    libgl1-mesa-dev \
                    libsdl1.2-dev \
                    libpostproc-dev \
                    freeglut3-dev \
                    libboost-python-dev \
                    libboost-log-dev \
                    libboost-regex-dev
elif [ $LINUX_ID == "ubuntu" ] && [ $LINUX_CODENAME == "focal" ]
then
    sudo apt-get -y install \
                    git \
                    cmake \
                    python-dev \
                    build-essential \
                    automake \
                    autoconf \
                    libpng16-16 \
                    libpng-dev \
                    libpng-tools \
                    libjpeg62-dev \
                    libexpat1-dev \
                    libgtk2.0-dev \
                    libgtk-3-dev \
                    libopenal-dev \
                    libogg-dev \
                    libvorbis-dev \
                    libgl1-mesa-dev \
                    libsdl1.2-dev \
                    libopengl0 \
                    libpostproc-dev \
                    freeglut3-dev \
                    libboost-python1.67-dev \
                    libboost-log1.67-dev \
                    libboost-regex1.67-dev
elif [ $LINUX_ID == "ubuntu" ] && [ $LINUX_CODENAME == "bionic" ]
then
    sudo apt-get -y install \
                    git \
                    cmake \
                    build-essential \
                    python-dev \
                    libgl1-mesa-glx \
                    freeglut3-dev \
                    libopenal-dev \
                    libsdl-gfx1.2-dev \
                    libvorbis-dev \
                    libjpeg-dev \
                    libpng-dev \
                    libgtk2.0-dev \
                    libgtk-3-dev \
                    libboost-python-dev \
                    libboost-log-dev \
                    libboost-regex-dev
elif [ $LINUX_ID == "ubuntu" ] && [ $LINUX_CODENAME == "xenial" ]
then
    sudo apt-get -y install \
                    git \
                    cmake \
                    build-essential \
                    python-dev \
                    libgl1-mesa-glx \
                    freeglut3-dev \
                    libopenal-dev \
                    libsdl-gfx1.2-dev \
                    libvorbis-dev \
                    libjpeg-dev \
                    libpng-dev \
                    libgtk2.0-dev \
                    libgtk-3-dev \
                    libboost-python-dev \
                    libboost-log-dev \
                    libboost-regex-dev
elif [ $LINUX_ID == "opensuse-leap" ]
then
    sudo zypper install -y  libboost_log1_66_0-devel \
                            libboost_python-py2_7-1_66_0-devel \
                            libboost_python-py3-1_66_0-devel \
                            libboost_system1_66_0-devel \
                            libboost_filesystem1_66_0-devel \
                            libboost_thread1_66_0-devel \
                            libboost_regex1_66_0-devel \
                            libboost_chrono1_66_0-devel \
                            libboost_atomic1_66_0-devel \
                            cmake \
                            gcc-c++ \
                            freeglut-devel \
                            libopenal0 \
                            openal-soft-devel \
                            libSDL-1_2-0 \
                            libSDL-devel \
                            libvorbis-devel \
                            libjpeg-turbo \
                            libjpeg62-devel \
                            libpng16-devel \
                            expat \
                            libexpat-devel \
                            libgtk-2_0-0 \
                            gtk2-devel \
                            libgtk-3-0 \
                            gtk3-devel \
                            python-devel \
                            python3-devel \
                            git \
                            rpm-build
elif [ $LINUX_ID == "fedora" ] && [ $LINUX_VERSION_ID -eq 32 ]
then
    sudo dnf install -y git \
                        cmake \
                        boost-devel \
                        boost-python3-devel \
                        freeglut-devel \
                        gcc-c++ \
                        openal-soft-devel \
                        SDL-devel \
                        libvorbis-devel \
                        libjpeg-turbo-devel \
                        libpng-devel \
                        expat-devel \
                        gtk2-devel \
                        gtk3-devel \
                        python3-devel \
                        rpm-build \
                        make
elif [ $LINUX_ID == "fedora" ] && ([ $LINUX_VERSION_ID -ge 30 ] && [ $LINUX_VERSION_ID -lt 32])
then
    sudo dnf install -y git \
                        cmake \
                        boost-devel \
                        boost-python2-devel \
                        boost-python3-devel \
                        freeglut-devel \
                        gcc-c++ \
                        openal-soft-devel \
                        SDL-devel \
                        libvorbis-devel \
                        libjpeg-turbo-devel \
                        libpng-devel \
                        expat-devel \
                        gtk2-devel \
                        gtk3-devel \
                        python2-devel \
                        python3-devel \
                        rpm-build \
                        make
elif [ $LINUX_ID == "centos" ] && [ $LINUX_VERSION_ID -eq 8 ]
then
    echo "Work in progress"
    sudo dnf install -y git \
                        cmake \
                        boost-devel \
                        boost-python3-devel \
                        freeglut-devel \
                        gcc-c++ \
                        openal-soft-devel \
                        SDL-devel \
                        libvorbis-devel \
                        libjpeg-turbo-devel \
                        libpng-devel \
                        expat-devel \
                        gtk2-devel \
                        gtk3-devel \
                        python3-devel \
                        rpm-build \
                        make
elif ([ $LINUX_ID == "rhel" ] || [ $LINUX_ID == "redhat" ]) && [ $LINUX_VERSION_ID -eq 8 ]
then
    echo "Work in progress"
    sudo dnf install -y git \
                        cmake \
                        boost-devel \
                        boost-python3-devel \
                        freeglut-devel \
                        gcc-c++ \
                        openal-soft-devel \
                        SDL-devel \
                        libvorbis-devel \
                        libjpeg-turbo-devel \
                        libpng-devel \
                        expat-devel \
                        gtk2-devel \
                        gtk3-devel \
                        python3-devel \
                        rpm-build \
                        make
else
    echo "Unsupported Linux distribution"
    exit 2
fi

echo "Bootstrapping finished!"
