#!/usr/bin/env bash
#====================================
# @file   : bootstrap
# @brief  : installs dependencies for building Vega Strike
# @usage  : sudo script/bootstrap 1 (to update all installed packages on the
#           system in the process)
#     or  : sudo script/bootstrap 0 (to skip updating, and just install the
#           new packages that are needed)
# @param  : just one parameter, either a 1 or a 0, to indicate whether or not to
#           UPDATE_ALL_SYSTEM_PACKAGES
#====================================
# Copyright (C) 2020-2024 Stephen G. Tuggy, Benjamen R. Meyer, and other Vega Strike contributors
#
# This file is part of Vega Strike.
#
# Vega Strike is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Vega Strike is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Vega Strike. If not, see <https://www.gnu.org/licenses/>.

set -e

echo "------------------------------"
echo "--- bootstrap | 2024-12-31 ---"
echo "------------------------------"

UPDATE_ALL_SYSTEM_PACKAGES="$1"

if [ -f /etc/os-release ]
then
    OS_RELEASE_LOCATION="/etc/os-release"
elif [ -f /usr/lib/os-release ]
then
    OS_RELEASE_LOCATION="/usr/lib/os-release"
else
    echo "os-release file not found; unable to continue"
    exit 1
fi
LINUX_ID=$(grep ^ID= $OS_RELEASE_LOCATION | sed 's/^ID=//' | tr -d '"\n')
echo "LINUX_ID = ${LINUX_ID}"
LINUX_CODENAME=$(grep ^VERSION_CODENAME= $OS_RELEASE_LOCATION | sed 's/^VERSION_CODENAME=//' | tr -d '"\n')
echo "LINUX_CODENAME = ${LINUX_CODENAME}"
LINUX_VERSION_ID=$(grep ^VERSION_ID= $OS_RELEASE_LOCATION | sed 's/^VERSION_ID=//' | tr -d '"\n')
echo "LINUX_VERSION_ID = ${LINUX_VERSION_ID}"

function bootstrapOnDebian()
{
  apt-get update

  if [ "${UPDATE_ALL_SYSTEM_PACKAGES}" -eq 1 ]
  then
    apt-get -qy upgrade
  fi

  case "$LINUX_CODENAME" in
    "bookworm")
      apt-get -qy install \
                      git \
                      cmake \
                      python3-dev \
                      build-essential \
                      automake \
                      autoconf \
                      libpng16-16 \
                      libpng-dev \
                      libpng-tools \
                      libjpeg62-turbo-dev \
                      libexpat1-dev \
                      libgtk-3-dev \
                      libopenal-dev \
                      libogg-dev \
                      libvorbis-dev \
                      libglvnd-dev \
                      libgl1-mesa-dev \
                      libsdl1.2-dev \
                      libsdl2-dev \
                      libpostproc-dev \
                      freeglut3-dev \
                      libboost-python-dev \
                      libboost-log-dev \
                      libboost-regex-dev \
                      libboost-program-options-dev \
                      libxmu-dev \
                      clang \
                      lsb-release
      ;;
    "bullseye")
      apt-get -qy install \
                      git \
                      cmake \
                      python3-dev \
                      build-essential \
                      automake \
                      autoconf \
                      libpng16-16 \
                      libpng-dev \
                      libpng-tools \
                      libjpeg62-turbo-dev \
                      libexpat1-dev \
                      libgtk-3-dev \
                      libopenal-dev \
                      libogg-dev \
                      libvorbis-dev \
                      libglvnd-dev \
                      libgl1-mesa-dev \
                      libsdl1.2-dev \
                      libsdl2-dev \
                      libpostproc-dev \
                      freeglut3-dev \
                      libboost-python-dev \
                      libboost-log-dev \
                      libboost-regex-dev \
                      libboost-program-options-dev \
                      libxmu-dev \
                      clang \
                      lsb-release
      ;;
    "buster")
      echo "Sorry, Debian buster is no longer supported"
      ;;
    "stretch")
      echo "Sorry, Debian stretch is no longer supported"
      exit 2
      ;;
    *)
      echo "Sorry, this version of Debian is unsupported"
      exit 2
      ;;
  esac
}

function bootstrapOnUbuntu()
{
  apt-get update

  if [ "${UPDATE_ALL_SYSTEM_PACKAGES}" -eq 1 ]
  then
    apt-get -qy upgrade
  fi

  case "$LINUX_CODENAME" in
    "noble")
      apt-get -qy install \
                      git \
                      cmake \
                      python3-dev \
                      build-essential \
                      automake \
                      autoconf \
                      libpng16-16 \
                      libpng-dev \
                      libpng-tools \
                      libjpeg-turbo8-dev \
                      libexpat1-dev \
                      libgdk-pixbuf-2.0-dev \
                      libgtk-3-dev \
                      libopenal-dev \
                      libogg-dev \
                      libvorbis-dev \
                      libglvnd-dev \
                      libgl1-mesa-dev \
                      libsdl1.2-dev \
                      libsdl2-dev \
                      libopengl0 \
                      libpostproc-dev \
                      freeglut3-dev \
                      libboost-python-dev \
                      libboost-log-dev \
                      libboost-regex-dev \
                      libboost-program-options-dev \
                      libxmu-dev \
                      clang \
                      lsb-release
      ;;
    "jammy")
      apt-get -qy install \
                      git \
                      cmake \
                      python3-dev \
                      build-essential \
                      automake \
                      autoconf \
                      libpng16-16 \
                      libpng-dev \
                      libpng-tools \
                      libjpeg-turbo8-dev \
                      libexpat1-dev \
                      libgdk-pixbuf-2.0-dev \
                      libgtk-3-dev \
                      libopenal-dev \
                      libogg-dev \
                      libvorbis-dev \
                      libglvnd-dev \
                      libgl1-mesa-dev \
                      libsdl1.2-dev \
                      libsdl2-dev \
                      libopengl0 \
                      libpostproc-dev \
                      freeglut3-dev \
                      libboost-python-dev \
                      libboost-log-dev \
                      libboost-regex-dev \
                      libboost-program-options-dev \
                      libxmu-dev \
                      clang \
                      lsb-release
      ;;
    "focal")
      apt-get -qy install \
                      git \
                      cmake \
                      build-essential \
                      automake \
                      autoconf \
                      libpng16-16 \
                      libpng-dev \
                      libpng-tools \
                      libjpeg62-dev \
                      libexpat1-dev \
                      libgtk-3-dev \
                      libopenal-dev \
                      libogg-dev \
                      libvorbis-dev \
                      libglvnd-dev \
                      libgl1-mesa-dev \
                      libsdl1.2-dev \
                      libsdl2-dev \
                      libopengl0 \
                      libpostproc-dev \
                      freeglut3-dev \
                      libboost-python-dev \
                      libboost-log-dev \
                      libboost-regex-dev \
                      libboost-program-options-dev \
                      libxmu-dev \
                      clang \
                      lsb-release
      ;;
    "bionic")
      echo "Sorry, Ubuntu bionic is no longer supported"
      exit 2
      ;;
    "impish")
      echo "Sorry, Ubuntu impish is no longer supported"
      exit 2
      ;;
    "hirsute")
      echo "Sorry, Ubuntu hirsute is no longer supported"
      exit 2
      ;;
    "xenial")
      echo "Sorry, Ubuntu xenial is no longer supported"
      exit 2
      ;;
    *)
      echo "Sorry, this version of Ubuntu is unsupported"
      exit 2
      ;;
  esac
}

function bootstrapOnPopOS ()
{
  apt-get update

  if [ "${UPDATE_ALL_SYSTEM_PACKAGES}" -eq 1 ]
  then
    apt-get -qy upgrade
  fi

  case "$LINUX_CODENAME" in
    "jammy")
      apt-get -qy install \
                      git \
                      cmake \
                      python3-dev \
                      build-essential \
                      automake \
                      autoconf \
                      libpng16-16 \
                      libpng-dev \
                      libpng-tools \
                      libjpeg-turbo8-dev \
                      libexpat1-dev \
                      libgdk-pixbuf-2.0-dev \
                      libgtk-3-dev \
                      libopenal-dev \
                      libogg-dev \
                      libvorbis-dev \
                      libglvnd-dev \
                      libgl1-mesa-dev \
                      libsdl1.2-dev \
                      libsdl2-dev \
                      libopengl0 \
                      libpostproc-dev \
                      freeglut3-dev \
                      libboost-python-dev \
                      libboost-log-dev \
                      libboost-regex-dev \
                      libboost-program-options-dev \
                      libxmu-dev \
                      clang \
                      lsb-release
      ;;
    "noble")
      apt-get -qy install \
                      git \
                      cmake \
                      python3-dev \
                      build-essential \
                      automake \
                      autoconf \
                      libpng16-16 \
                      libpng-dev \
                      libpng-tools \
                      libjpeg-turbo8-dev \
                      libexpat1-dev \
                      libgdk-pixbuf-2.0-dev \
                      libgtk-3-dev \
                      libopenal-dev \
                      libogg-dev \
                      libvorbis-dev \
                      libglvnd-dev \
                      libgl1-mesa-dev \
                      libsdl1.2-dev \
                      libsdl2-dev \
                      libopengl0 \
                      libpostproc-dev \
                      freeglut3-dev \
                      libboost-python-dev \
                      libboost-log-dev \
                      libboost-regex-dev \
                      libboost-program-options-dev \
                      libxmu-dev \
                      clang \
                      lsb-release
      ;;
    *)
      echo "Sorry, this version of Pop! OS is not currently supported"
      exit 2
      ;;
  esac
}

function bootstrapOnLinuxMint ()
{
  apt-get update

  if [ "${UPDATE_ALL_SYSTEM_PACKAGES}" -eq 1 ]
  then
    apt-get -qy upgrade
  fi

  case "$LINUX_CODENAME" in
    "wilma")
      apt-get -qy install \
                      git \
                      cmake \
                      python3-dev \
                      build-essential \
                      automake \
                      autoconf \
                      libpng16-16 \
                      libpng-dev \
                      libpng-tools \
                      libjpeg-turbo8-dev \
                      libexpat1-dev \
                      libgdk-pixbuf-2.0-dev \
                      libgtk-3-dev \
                      libopenal-dev \
                      libogg-dev \
                      libvorbis-dev \
                      libglvnd-dev \
                      libgl1-mesa-dev \
                      libsdl1.2-compat-dev \
                      libsdl2-dev \
                      libopengl0 \
                      libpostproc-dev \
                      freeglut3-dev \
                      libboost-python-dev \
                      libboost-log-dev \
                      libboost-regex-dev \
                      libboost-program-options-dev \
                      libxmu-dev \
                      clang \
                      lsb-release
      ;;
    "virginia")
      apt-get -qy install \
                      git \
                      cmake \
                      python3-dev \
                      build-essential \
                      automake \
                      autoconf \
                      libpng16-16 \
                      libpng-dev \
                      libpng-tools \
                      libjpeg-turbo8-dev \
                      libexpat1-dev \
                      libgdk-pixbuf-2.0-dev \
                      libgtk-3-dev \
                      libopenal-dev \
                      libogg-dev \
                      libvorbis-dev \
                      libglvnd-dev \
                      libgl1-mesa-dev \
                      libsdl1.2-compat-dev \
                      libsdl2-dev \
                      libopengl0 \
                      libpostproc-dev \
                      freeglut3-dev \
                      libboost-python-dev \
                      libboost-log-dev \
                      libboost-regex-dev \
                      libboost-program-options-dev \
                      libxmu-dev \
                      clang \
                      lsb-release
      ;;
    "victoria")
      apt-get -qy install \
                      git \
                      cmake \
                      python3-dev \
                      build-essential \
                      automake \
                      autoconf \
                      libpng16-16 \
                      libpng-dev \
                      libpng-tools \
                      libjpeg-turbo8-dev \
                      libexpat1-dev \
                      libgdk-pixbuf-2.0-dev \
                      libgtk-3-dev \
                      libopenal-dev \
                      libogg-dev \
                      libvorbis-dev \
                      libglvnd-dev \
                      libgl1-mesa-dev \
                      libsdl1.2-compat-dev \
                      libsdl2-dev \
                      libopengl0 \
                      libpostproc-dev \
                      freeglut3-dev \
                      libboost-python-dev \
                      libboost-log-dev \
                      libboost-regex-dev \
                      libboost-program-options-dev \
                      libxmu-dev \
                      clang \
                      lsb-release
      ;;
    "vera")
      apt-get -qy install \
                      git \
                      cmake \
                      python3-dev \
                      build-essential \
                      automake \
                      autoconf \
                      libpng16-16 \
                      libpng-dev \
                      libpng-tools \
                      libjpeg-turbo8-dev \
                      libexpat1-dev \
                      libgdk-pixbuf-2.0-dev \
                      libgtk-3-dev \
                      libopenal-dev \
                      libogg-dev \
                      libvorbis-dev \
                      libglvnd-dev \
                      libgl1-mesa-dev \
                      libsdl1.2-compat-dev \
                      libsdl2-dev \
                      libopengl0 \
                      libpostproc-dev \
                      freeglut3-dev \
                      libboost-python-dev \
                      libboost-log-dev \
                      libboost-regex-dev \
                      libboost-program-options-dev \
                      libxmu-dev \
                      clang \
                      lsb-release
      ;;
    "vanessa")
      apt-get -qy install \
                      git \
                      cmake \
                      python3-dev \
                      build-essential \
                      automake \
                      autoconf \
                      libpng16-16 \
                      libpng-dev \
                      libpng-tools \
                      libjpeg-turbo8-dev \
                      libexpat1-dev \
                      libgdk-pixbuf-2.0-dev \
                      libgtk-3-dev \
                      libopenal-dev \
                      libogg-dev \
                      libvorbis-dev \
                      libglvnd-dev \
                      libgl1-mesa-dev \
                      libsdl1.2-dev \
                      libsdl2-dev \
                      libopengl0 \
                      libpostproc-dev \
                      freeglut3-dev \
                      libboost-python-dev \
                      libboost-log-dev \
                      libboost-regex-dev \
                      libboost-program-options-dev \
                      libxmu-dev \
                      clang \
                      lsb-release
      ;;
    "ulyana")
      apt-get -qy install \
                      git \
                      cmake \
                      build-essential \
                      automake \
                      autoconf \
                      libpng16-16 \
                      libpng-dev \
                      libpng-tools \
                      libjpeg62-dev \
                      libexpat1-dev \
                      libgtk-3-dev \
                      libopenal-dev \
                      libogg-dev \
                      libvorbis-dev \
                      libglvnd-dev \
                      libgl1-mesa-dev \
                      libsdl1.2-dev \
                      libsdl2-dev \
                      libopengl0 \
                      libpostproc-dev \
                      freeglut3-dev \
                      libboost-python-dev \
                      libboost-log-dev \
                      libboost-regex-dev \
                      libboost-program-options-dev \
                      libxmu-dev \
                      clang \
                      lsb-release
      ;;
    *)
      echo "This version of Linux Mint is not directly supported. You may be able to use the corresponding Ubuntu installation package"
      exit 2
      ;;
  esac
}

function bootstrapOnOpenSuseLeap ()
{
  case "${LINUX_VERSION_ID}" in
    "15.2")
      zypper --non-interactive install -y \
                              libboost_log1_66_0-devel \
                              libboost_python-py3-1_66_0-devel \
                              libboost_system1_66_0-devel \
                              libboost_filesystem1_66_0-devel \
                              libboost_thread1_66_0-devel \
                              libboost_regex1_66_0-devel \
                              libboost_chrono1_66_0-devel \
                              libboost_atomic1_66_0-devel \
                              libboost_program_options1_66_0-devel \
                              cmake \
                              gcc-c++ \
                              freeglut-devel \
                              libopenal0 \
                              openal-soft-devel \
                              libSDL-1_2-0 \
                              libSDL-devel \
                              libSDL2-devel \
                              libvorbis-devel \
                              libglvnd-devel \
                              libjpeg-turbo \
                              libjpeg62-devel \
                              libpng16-devel \
                              expat \
                              libexpat-devel \
                              libgtk-3-0 \
                              gtk3-devel \
                              python3-devel \
                              git \
                              rpm-build \
                              clang
      ;;
    "15.3")
      zypper --non-interactive install -y \
                              libboost_log1_66_0-devel \
                              libboost_python-py3-1_66_0-devel \
                              libboost_system1_66_0-devel \
                              libboost_filesystem1_66_0-devel \
                              libboost_thread1_66_0-devel \
                              libboost_regex1_66_0-devel \
                              libboost_chrono1_66_0-devel \
                              libboost_atomic1_66_0-devel \
                              libboost_program_options1_66_0-devel \
                              cmake \
                              gcc-c++ \
                              freeglut-devel \
                              libopenal0 \
                              openal-soft-devel \
                              libSDL-1_2-0 \
                              libSDL-devel \
                              libSDL2-devel \
                              libvorbis-devel \
                              libglvnd-devel \
                              libjpeg-turbo \
                              libjpeg62-devel \
                              libpng16-devel \
                              expat \
                              libexpat-devel \
                              libgtk-3-0 \
                              gtk3-devel \
                              python3-devel \
                              git \
                              rpm-build \
                              clang
      ;;
    "15.4")
      zypper --non-interactive install -y \
                              libboost_log1_75_0-devel \
                              libboost_python-py3-1_75_0-devel \
                              libboost_system1_75_0-devel \
                              libboost_filesystem1_75_0-devel \
                              libboost_thread1_75_0-devel \
                              libboost_regex1_75_0-devel \
                              libboost_chrono1_75_0-devel \
                              libboost_atomic1_75_0-devel \
                              libboost_program_options1_75_0-devel \
                              cmake \
                              gcc-c++ \
                              freeglut-devel \
                              libopenal0 \
                              openal-soft-devel \
                              libSDL-1_2-0 \
                              libSDL-devel \
                              libSDL2-devel \
                              libvorbis-devel \
                              libglvnd-devel \
                              libjpeg-turbo \
                              libjpeg62-devel \
                              libpng16-devel \
                              expat \
                              libexpat-devel \
                              libgtk-3-0 \
                              gtk3-devel \
                              python3-devel \
                              git \
                              rpm-build \
                              clang
      ;;
    "15.5")
      zypper --non-interactive install -y \
                              libboost_log1_75_0-devel \
                              libboost_python-py3-1_75_0-devel \
                              libboost_system1_75_0-devel \
                              libboost_filesystem1_75_0-devel \
                              libboost_thread1_75_0-devel \
                              libboost_regex1_75_0-devel \
                              libboost_chrono1_75_0-devel \
                              libboost_atomic1_75_0-devel \
                              libboost_program_options1_75_0-devel \
                              cmake \
                              gcc-c++ \
                              freeglut-devel \
                              libopenal0 \
                              openal-soft-devel \
                              libSDL-1_2-0 \
                              libSDL-devel \
                              libSDL2-devel \
                              libvorbis-devel \
                              libglvnd-devel \
                              libjpeg-turbo \
                              libjpeg62-devel \
                              libpng16-devel \
                              expat \
                              libexpat-devel \
                              libgtk-3-0 \
                              gtk3-devel \
                              python3-devel \
                              git \
                              rpm-build \
                              clang
      ;;
    "15.6")
      zypper --non-interactive install -y \
                              libboost_log1_75_0-devel \
                              libboost_python-py3-1_75_0-devel \
                              libboost_system1_75_0-devel \
                              libboost_filesystem1_75_0-devel \
                              libboost_thread1_75_0-devel \
                              libboost_regex1_75_0-devel \
                              libboost_chrono1_75_0-devel \
                              libboost_atomic1_75_0-devel \
                              libboost_program_options1_75_0-devel \
                              cmake \
                              gcc-c++ \
                              freeglut-devel \
                              libopenal0 \
                              openal-soft-devel \
                              libSDL-1_2-0 \
                              libSDL-devel \
                              libSDL2-devel \
                              libvorbis-devel \
                              libglvnd-devel \
                              libjpeg-turbo \
                              libjpeg62-devel \
                              libpng16-devel \
                              expat \
                              libexpat-devel \
                              libgtk-3-0 \
                              gtk3-devel \
                              python3-devel \
                              git \
                              rpm-build \
                              clang
      ;;
    *)
      echo "Sorry, this version of openSUSE Leap is unsupported"
      exit 2
      ;;
  esac
}

function bootstrapOnFedora ()
{
  case "${LINUX_VERSION_ID}" in
    30)
      dnf install -y \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    31)
      dnf install -y \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    32)
      dnf install -y \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    33)
      dnf install -y \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    34)
      dnf install -y \
                          git \
                          cmake \
                          boost-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    35)
      dnf install -y \
                          git \
                          cmake \
                          boost-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    36)
      dnf install -y \
                          git \
                          cmake \
                          boost-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    37)
      dnf install -y \
                          git \
                          cmake \
                          boost-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    38)
      dnf install -y \
                          git \
                          cmake \
                          boost-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    39)
      dnf install -y \
                          git \
                          cmake \
                          boost-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    40)
      dnf install -y \
                          git \
                          cmake \
                          boost-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    41)
      dnf install -y \
                          git \
                          cmake \
                          boost-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    *)
      echo "Sorry, this version of Fedora is unsupported"
      exit 2
      ;;
  esac
}

function bootstrapOnCentOS ()
{
  case "${LINUX_VERSION_ID}" in
    "8")
      dnf -y install dnf-plugins-core
      dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      dnf config-manager --set-enabled PowerTools
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.0")
      dnf -y install dnf-plugins-core
      dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      dnf config-manager --set-enabled PowerTools
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    *)
      echo "Sorry, this version of CentOS is unsupported"
      exit 2
      ;;
  esac
}

function bootstrapOnRedHat ()
{
  case "${LINUX_VERSION_ID}" in
    "8.0")
      dnf -y install dnf-plugins-core
      dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      dnf config-manager --set-enabled PowerTools
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.1")
      dnf -y install dnf-plugins-core
      dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      dnf config-manager --set-enabled PowerTools
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.2")
      dnf -y install dnf-plugins-core
      dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      dnf config-manager --set-enabled PowerTools
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.3")
      dnf -y install dnf-plugins-core
      dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      dnf config-manager --set-enabled PowerTools
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.4")
      dnf -y install dnf-plugins-core
      dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      dnf config-manager --set-enabled PowerTools
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.5")
      dnf -y install dnf-plugins-core
      dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      dnf config-manager --set-enabled PowerTools
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.6")
      dnf -y install dnf-plugins-core
      dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      dnf config-manager --set-enabled PowerTools
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.7")
      dnf -y install dnf-plugins-core
      dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      dnf config-manager --set-enabled PowerTools
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.8")
      dnf -y install dnf-plugins-core
      dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      dnf config-manager --set-enabled PowerTools
      dnf -y install \
                          git \
                          cmake \
                          python3.11-devel \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.9")
      dnf -y install dnf-plugins-core
      dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      dnf config-manager --set-enabled PowerTools
      dnf -y install \
                          git \
                          cmake \
                          python3.11-devel \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.10")
      dnf -y install dnf-plugins-core
      dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      dnf config-manager --set-enabled PowerTools
      dnf -y install \
                          git \
                          cmake \
                          python3.11-devel \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "9.0")
      dnf -y install dnf-plugins-core
      dnf config-manager --set-enabled devel
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "9.1")
      dnf -y install dnf-plugins-core
      dnf config-manager --set-enabled devel
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "9.2")
      dnf -y install dnf-plugins-core
      dnf config-manager --set-enabled devel
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "9.3")
      dnf -y install dnf-plugins-core
      dnf config-manager --set-enabled devel
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "9.4")
      dnf -y install dnf-plugins-core
      dnf config-manager --set-enabled devel
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "9.5")
      dnf -y install dnf-plugins-core
      dnf config-manager --set-enabled devel
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    *)
      echo "Sorry, this version of Red Hat is unsupported"
      exit 2
      ;;
  esac
}

function bootstrapOnRockyLinux ()
{
  case "${LINUX_VERSION_ID}" in
    "8.0")
      dnf -y install dnf-plugins-core
      dnf -y install epel-release
      dnf config-manager --enable epel
      dnf config-manager --set-enabled powertools
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.1")
      dnf -y install dnf-plugins-core
      dnf -y install epel-release
      dnf config-manager --enable epel
      dnf config-manager --set-enabled powertools
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.2")
      dnf -y install dnf-plugins-core
      dnf -y install epel-release
      dnf config-manager --enable epel
      dnf config-manager --set-enabled powertools
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.3")
      dnf -y install dnf-plugins-core
      dnf -y install epel-release
      dnf config-manager --enable epel
      dnf config-manager --set-enabled powertools
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.4")
      dnf -y install dnf-plugins-core
      dnf -y install epel-release
      dnf config-manager --enable epel
      dnf config-manager --set-enabled powertools
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.5")
      dnf -y install dnf-plugins-core
      dnf -y install epel-release
      dnf config-manager --enable epel
      dnf config-manager --set-enabled powertools
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.6")
      dnf -y install dnf-plugins-core
      dnf -y install epel-release
      dnf config-manager --enable epel
      dnf config-manager --set-enabled powertools
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.7")
      dnf -y install dnf-plugins-core
      dnf -y install epel-release
      dnf config-manager --enable epel
      dnf config-manager --set-enabled powertools
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.8")
      dnf -y install dnf-plugins-core
      dnf -y install epel-release
      dnf config-manager --enable epel
      dnf config-manager --set-enabled powertools
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3.11-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.9")
      dnf -y install dnf-plugins-core
      dnf -y install epel-release
      dnf config-manager --enable epel
      dnf config-manager --set-enabled powertools
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3.11-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "8.10")
      dnf -y install dnf-plugins-core
      dnf -y install epel-release
      dnf config-manager --enable epel
      dnf config-manager --set-enabled powertools
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          SDL-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3.11-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "9.0")
      dnf -y install dnf-plugins-core
      dnf config-manager --set-enabled devel
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "9.1")
      dnf -y install dnf-plugins-core
      dnf config-manager --set-enabled devel
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "9.2")
      dnf -y install dnf-plugins-core
      dnf config-manager --set-enabled devel
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "9.3")
      dnf -y install dnf-plugins-core
      dnf config-manager --set-enabled devel
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "9.4")
      dnf -y install dnf-plugins-core
      dnf config-manager --set-enabled devel
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    "9.5")
      dnf -y install dnf-plugins-core
      dnf config-manager --set-enabled devel
      dnf -y update
      dnf -y install \
                          git \
                          cmake \
                          boost-devel \
                          boost-python3-devel \
                          freeglut-devel \
                          gcc-c++ \
                          openal-soft-devel \
                          sdl12-compat-devel \
                          SDL2-devel \
                          libvorbis-devel \
                          libglvnd-devel \
                          libjpeg-turbo-devel \
                          libpng-devel \
                          expat-devel \
                          gtk3-devel \
                          python3-devel \
                          rpm-build \
                          make \
                          clang
      ;;
    *)
      echo "Sorry, this version of Rocky Linux is unsupported"
      exit 2
      ;;
  esac
}

function bootstrapOnManjaro ()
{
    pacman -S --refresh --noconfirm cmake \
                   boost \
                   clang \
                   gcc \
                   gcc-libs \
                   sdl \
                   sdl2 \
                   expat \
                   gtk3 \
                   libglvnd \
                   mesa \
                   python \
                   autoconf \
                   automake \
                   freeglut \
                   git \
                   libjpeg-turbo \
                   libpng \
                   libvorbis \
                   libxmu \
                   openal \
                   make
}

function bootstrapOnFuntoo ()
{
  ego sync
  dispatch-conf
  # enable `autounmask-write` so that USE flags
  # change in the image appropriately
  USE="-libffi -userland_GNU gles2 X" emerge --autounmask-write \
        cmake \
        boost \
        libsdl \
        libsdl2 \
        expat \
        gtk3 \
        libglvnd \
        mesa \
        python \
        autoconf \
        automake \
        freeglut \
        git \
        libjpeg-turbo \
        libpng \
        libvorbis \
        libXmu \
        openal \
        make \
        x11-libs/gtk+
}

function bootstrapOnArch ()
{
  # NOTE: Arch requires GCC 12 right now
  # also installing latest GCC.
  pacman -Sy --noconfirm \
        base-devel \
        cmake \
        boost \
        llvm \
        clang \
        gcc \
        gcc12 \
        sdl \
        sdl2 \
        expat \
        gtk3 \
        libglvnd \
        mesa \
        python \
        freeglut \
        git \
        libjpeg-turbo \
        libpng \
        libvorbis \
        libxmu \
        openal \
        make
}

case "${LINUX_ID}" in
  "debian")
    bootstrapOnDebian
    ;;
  "ubuntu")
    bootstrapOnUbuntu
    ;;
  "pop")
    bootstrapOnPopOS
    ;;
  "linuxmint")
    bootstrapOnLinuxMint
    ;;
  "opensuse-leap")
    bootstrapOnOpenSuseLeap
    ;;
  "fedora")
    bootstrapOnFedora
    ;;
  "centos")
    bootstrapOnCentOS
    ;;
  "rhel")
    bootstrapOnRedHat
    ;;
  "redhat")
    bootstrapOnRedHat
    ;;
  "rocky")
    bootstrapOnRockyLinux
    ;;
  "manjaro")
    bootstrapOnManjaro
    ;;
  "funtoo")
    bootstrapOnFuntoo
    ;;
  "arch")
    bootstrapOnArch
    ;;
  *)
    echo "Sorry, unrecognized/unsupported Linux distribution"
    exit 2
    ;;
esac

mkdir -p /usr/src/Vega-Strike-Engine-Source

echo "Bootstrapping finished!"
