#!/usr/bin/env bash
#====================================
# @file   : build
# @brief  : build VegaStrike
# @usage  : ./script/build
# @param  : none
#====================================

#============ DESCRIPTION ===========
# This script is making a clean build of VegaStrike.
# After this, it copies the relevant files to the 'bin' directory.
# The steps for creating this script were taken from the projects wiki:
# https://github.com/Taose/Vegastrike-taose/wiki/How-to-Build
#====================================

# Copyright (C) 2020-2025 Stephen G. Tuggy and other Vega Strike contributors.
#
# https://github.com/vegastrike/Vega-Strike-Engine-Source
#
# This file is part of Vega Strike.
#
# Vega Strike is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Vega Strike is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Vega Strike.  If not, see <https://www.gnu.org/licenses/>.


set -e

echo "--------------------------"
echo "--- build | 2025-11-29 ---"
echo "--------------------------"

#----------------------------------
# validate parameters
#----------------------------------

ROOT_DIR=$(pwd)
echo "ROOT_DIR: ${ROOT_DIR}"
BUILD_DIR="${ROOT_DIR}/build"
echo "BUILD_DIR: ${BUILD_DIR}"
BIN_DIR="${ROOT_DIR}/bin"
SRC_DIR="${ROOT_DIR}/engine"
COMMAND=""

# -p creates if the target doesn't exist, noop otherwise
mkdir -pv "${BUILD_DIR}" && cd "${BUILD_DIR}"

# configure libraries and prepare for the Debug build having -Werror set,
# thus gating VS commits on being warning-free at some point in the near
# future -- see https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/50
cmake "$@" -DINSTALL_GTEST="${INSTALL_GTEST:-ON}" -DUSE_GTEST="${USE_GTEST:-ON}" "${SRC_DIR}"

# for a clean build only
# mut we can do it manually
#make clean

MAX_THREADS_TO_BUILD_WITH=8
NUM_THREADS_TO_BUILD_WITH=$(getconf _NPROCESSORS_ONLN)
if [ ${NUM_THREADS_TO_BUILD_WITH} -gt ${MAX_THREADS_TO_BUILD_WITH} ]
then
    NUM_THREADS_TO_BUILD_WITH=${MAX_THREADS_TO_BUILD_WITH}
fi

VERBOSE=1 cmake --build "${BUILD_DIR}" -j ${NUM_THREADS_TO_BUILD_WITH}

cd "${ROOT_DIR}"

mkdir -pv "${BIN_DIR}"

declare -a files_to_copy_if_they_exist=("${BUILD_DIR}/vegastrike-engine" "${BUILD_DIR}/setup/vegasettings" "${BUILD_DIR}/objconv/vega-meshtool")
declare -a directories_to_copy_if_they_exist=("${BUILD_DIR}/vegastrike-engine.app" "${BUILD_DIR}/setup/vegasettings.app")

for i in "${files_to_copy_if_they_exist[@]}"
do
    if [ -f "$i" ]
    then
        cp -v "$i" "${BIN_DIR}"/
    fi
done

for i in "${directories_to_copy_if_they_exist[@]}"
do
    if [ -d "$i" ]
    then
        cp -rv "$i" "${BIN_DIR}"/
    fi
done
