#!/usr/bin/env bash
#====================================
# @file   : build
# @brief  : build VegaStrike
# @usage  : ./script/build --preset-name=VS2022Win64-pie-enabled-RelWithDebInfo
# @param  : preset-name=, build-type=
#====================================

#============ DESCRIPTION ===========
# This script builds VegaStrike.
# After this, it copies the relevant files to the 'bin' directory.
# The steps for creating this script were taken from the projects wiki:
# https://github.com/Taose/Vegastrike-taose/wiki/How-to-Build
#====================================

# Copyright (C) 2020-2026 Stephen G. Tuggy and other Vega Strike contributors.
#
# https://github.com/vegastrike/Vega-Strike-Engine-Source
#
# This file is part of Vega Strike.
#
# Vega Strike is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Vega Strike is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Vega Strike.  If not, see <https://www.gnu.org/licenses/>.


set -e

echo "--------------------------"
echo "--- build | 2026-03-11 ---"
echo "--------------------------"

#----------------------------------
# validate parameters
#----------------------------------

while [ $# -gt 0 ]; do
  case "$1" in
    --preset_name=*)
      preset_name="${1#*=}"
      ;;
    --preset-name=*)
      preset_name="${1#*=}"
      ;;
    --build_type=*)
      build_type="${1#*=}"
      ;;
    --build-type=*)
      build_type="${1#*=}"
      ;;
    *)
      printf "***************************\n"
      printf "* Error: Invalid argument.*\n"
      printf "***************************\n"
      exit 1
      ;;
  esac
  shift
done

ROOT_DIR=$(pwd)
echo "ROOT_DIR: ${ROOT_DIR}"
BUILD_DIR="${ROOT_DIR}/build"
echo "BUILD_DIR: ${BUILD_DIR}"
BIN_DIR="${ROOT_DIR}/bin"

# -p creates if the target doesn't exist, noop otherwise
mkdir -pv "${BUILD_DIR}"

cmake --preset "$preset_name"

MAX_THREADS_TO_BUILD_WITH=8
if [ -f ./script/num_cpus ] && [ -x ./script/num_cpus ]
then
  num_threads_to_build_with=$(./script/num_cpus)
elif [ -f ./num_cpus ] && [ -x ./num_cpus ]
then
  num_threads_to_build_with=$(./num_cpus)
else
  echo "Error locating num_cpus script"
  exit 3
fi

echo "Number of threads to build with before capping: $num_threads_to_build_with"
if [ ${num_threads_to_build_with} -gt ${MAX_THREADS_TO_BUILD_WITH} ]
then
  num_threads_to_build_with=${MAX_THREADS_TO_BUILD_WITH}
fi
echo "Number of threads to build with after capping: $num_threads_to_build_with"

VERBOSE=1 cmake --build --preset="build-${preset_name}" -j ${num_threads_to_build_with}

cd "${ROOT_DIR}"

mkdir -pv "${BIN_DIR}"

declare -a files_to_copy_if_they_exist=("${BUILD_DIR}/vegastrike-engine" "${BUILD_DIR}/setup/vegasettings" "${BUILD_DIR}/objconv/vega-meshtool")
declare -a directories_to_copy_if_they_exist=("${BUILD_DIR}/vegastrike-engine.app" "${BUILD_DIR}/setup/vegasettings.app")

for i in "${files_to_copy_if_they_exist[@]}"
do
  if [ -f "$i" ]
  then
    cp -v "$i" "${BIN_DIR}"/
  fi
done

for i in "${directories_to_copy_if_they_exist[@]}"
do
  if [ -d "$i" ]
  then
    cp -v "$i" "${BIN_DIR}"/
  fi
done
