#!/usr/bin/env bash
#====================================
# @file   : clean
# @brief  : cleans VegaStrike build
# @usage  : ./script/clean
# @param  : none
#====================================

echo "--------------------------"
echo "--- clean | 2025-01-01 ---"
echo "--------------------------"
echo "!!!warning!!! for strict developer use"
echo "--------------------------"

#----------------------------------
# validate parameters
#----------------------------------

ROOT_DIR=$(pwd)
BUILD_DIR=$ROOT_DIR/build
BIN_DIR=$ROOT_DIR/bin
DATA_DIR=$ROOT_DIR/data
SRC_DIR=$ROOT_DIR/engine

# delete build directory
if [ -n "$BUILD_DIR" ] && [ "$BUILD_DIR" != "/" ]
then
  echo "deleting build directory ($BUILD_DIR)"
  rm -rf "$BUILD_DIR"
fi

# delete .pyc files
echo "deleting compiled python files (*.pyc)"
find "$DATA_DIR" -name "*.pyc" -delete

# delete home vegastrike config
echo "deleting home vegastrike.config"
rm ~/.vegastrike/vegastrike.config
echo "run bin/vegasettings to create a new setup"
