#!/usr/bin/env bash
#====================================
# @file   : clean
# @brief  : cleans VegaStrike build
# @usage  : ./script/clean
# @param  : none
#====================================

echo "--------------------------"
echo "--- clean | 2020-08-17 ---"
echo "--------------------------"
echo "!!!warning!!! for strict developer use"
echo "--------------------------"

#----------------------------------
# validate parameters
#----------------------------------

ROOT_DIR=$(pwd)
BUILD_DIR=$ROOT_DIR/build
BIN_DIR=$ROOT_DIR/bin
DATA_DIR=$ROOT_DIR/data
SRC_DIR=$ROOT_DIR/engine

# delete build directory
echo "deleting build directory ($BUILD_DIR)"
rm -r $BUILD_DIR

# delete .pyc files
echo "deleting compiled python files (*.pyc)"
find $DATA_DIR -name "*.pyc" -delete

# delete home vegastrike config
echo "deleting home vegastrike.config"
rm ~/.vegastrike/vegastrike.config
echo "run bin/vegasettings to create a new setup"
