#!/usr/bin/env bash
#====================================
# @file   : setup
# @brief  : Sets up the Vega Strike project
#           in an initial state for
#           building/development
# @usage  : sudo script/setup
# @param  : none
#====================================

# set -e

echo "--------------------------"
echo "--- setup | 2026-06-18 ---"
echo "--------------------------"

script/bootstrap "$@"
script/clean
