EXECUTE_PROCESS(COMMAND brew --prefix
                OUTPUT_VARIABLE HomebrewPrefixOut
                ERROR_VARIABLE HomebrewPrefixErr
                OUTPUT_STRIP_TRAILING_WHITESPACE
                COMMAND_ERROR_IS_FATAL ANY)
SET(CMAKE_PREFIX_PATH "${HomebrewPrefixOut}:${CMAKE_PREFIX_PATH}")
SET(CMAKE_FIND_FRAMEWORK "LAST")
SET(CMAKE_FIND_APPBUNDLE "LAST")
SET(PythonInstalledVia "Homebrew" CACHE STRING "How Python was installed, such as via Homebrew or MacPorts")

EXECUTE_PROCESS(COMMAND brew --prefix libarchive
                OUTPUT_VARIABLE LIBARCHIVE_PREFIX
                ERROR_VARIABLE LIBARCHIVE_PREFIX_ERR
                OUTPUT_STRIP_TRAILING_WHITESPACE
                COMMAND_ERROR_IS_FATAL ANY)
SET(PKG_CONFIG_PATH "${LIBARCHIVE_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}")
MESSAGE(DEBUG "LIBARCHIVE_PREFIX: ${LIBARCHIVE_PREFIX}")
MESSAGE(DEBUG "PKG_CONFIG_PATH: ${PKG_CONFIG_PATH}")
SET(LibArchive_ROOT "${LIBARCHIVE_PREFIX}")
MESSAGE(DEBUG "LibArchive_ROOT ${LibArchive_ROOT}")
#SET(LibArchive_INCLUDE_DIR:PATH "${LIBARCHIVE_PREFIX}/include")
#SET(LibArchive_LIBRARY "${LIBARCHIVE_PREFIX}/lib")
#SET(LibArchive_LIBRARIES:FILEPATH "${LibArchive_LIBRARY}/libarchive.dylib")

#FIND_LIBRARY(LibArchive
#        NAMES LibArchive
#        REQUIRED)
#MESSAGE(DEBUG "LibArchive_INCLUDE_DIR: ${LibArchive_INCLUDE_DIR}")
#MESSAGE(DEBUG "LibArchive_INCLUDE_DIRs: ${LibArchive_INCLUDE_DIRs}")
#MESSAGE(DEBUG "LibArchive_LIBRARY: ${LibArchive_LIBRARY}")
#MESSAGE(DEBUG "LibArchive_LIBRARY_DIR: ${LibArchive_LIBRARY_DIR}")
#MESSAGE(DEBUG "LibArchive_LIBRARY_DIRS: ${LibArchive_LIBRARY_DIRS}")

