EXECUTE_PROCESS(COMMAND brew --prefix
                OUTPUT_VARIABLE HomebrewPrefixOut
                ERROR_VARIABLE HomebrewPrefixErr
                OUTPUT_STRIP_TRAILING_WHITESPACE)
SET(CMAKE_PREFIX_PATH "${HomebrewPrefixOut}:${CMAKE_PREFIX_PATH}")
SET(CMAKE_FIND_FRAMEWORK "LAST")
SET(CMAKE_FIND_APPBUNDLE "LAST")
SET(PythonInstalledVia "Homebrew" CACHE STRING "How Python was installed, such as via Homebrew or MacPorts")

EXECUTE_PROCESS(COMMAND homebrew --prefix libarchive
                OUTPUT_VARIABLE LIBARCHIVE_PREFIX
                ERROR_VARIABLE LIBARCHIVE_PREFIX_ERR
                OUTPUT_STRIP_TRAILING_WHITESPACE)
SET(PKG_CONFIG_PATH "${LIBARCHIVE_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}")
SET(LibArchive_INCLUDE_DIR "${LIBARCHIVE_PREFIX}/include")
SET(LibArchive_LIBRARY "${LIBARCHIVE_PREFIX}/lib")

FIND_PACKAGE(LibArchive REQUIRED)

MESSAGE(STATUS "LibArchive_INCLUDE_DIRS: ${LibArchive_INCLUDE_DIRS}")
MESSAGE(STATUS "LibArchive_INCLUDE_DIR: ${LibArchive_INCLUDE_DIR}")

SET(LibArchive_INCLUDE_DIR "${LIBARCHIVE_PREFIX}/include")
SET(LibArchive_LIB_DIR "${LIBARCHIVE_PREFIX}/lib")

#SET(CMAKE_FIND_FRAMEWORK "LAST")
#SET(CMAKE_FIND_APPBUNDLE "")
