name: Linux-PR
permissions:
  contents: read
  pull-requests: read

on: [ pull_request ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    continue-on-error: ${{ matrix.allow_failure }}

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - FROM:     'ubuntu:questing'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            INSTALL_GTEST: 1
            USE_GTEST: 1
            allow_failure: false
          - FROM:     'ubuntu:noble'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            INSTALL_GTEST: 1
            USE_GTEST: 1
            allow_failure: false
          - FROM:     'ubuntu:noble'
            COMPILER: 'clang'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            INSTALL_GTEST: 1
            USE_GTEST: 1
            allow_failure: false
          - FROM:     'linuxmintd/mint22.2-amd64'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            INSTALL_GTEST: 1
            USE_GTEST: 1
            allow_failure: false
          - FROM:     'linuxmintd/mint22-amd64'
            COMPILER: 'clang'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            INSTALL_GTEST: 1
            USE_GTEST: 1
            allow_failure: false
          - FROM:     'dhi.io/python:3.13-debian13-dev'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            INSTALL_GTEST: 1
            USE_GTEST: 1
            allow_failure: false
          - FROM:     'debian:bookworm'
            COMPILER: 'clang'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            INSTALL_GTEST: 1
            USE_GTEST: 1
            allow_failure: false
          - FROM:     'fedora:43'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-enabled-glvnd-RelWithDebInfo'
            INSTALL_GTEST: 1
            USE_GTEST: 1
            allow_failure: false
          - FROM:     'fedora:42'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-enabled-glvnd-RelWithDebInfo'
            INSTALL_GTEST: 1
            USE_GTEST: 1
            allow_failure: false
          - FROM:     'fedora:41'
            COMPILER: 'clang'
            preset-name: 'linux-unix-makefiles-pie-enabled-glvnd-RelWithDebInfo'
            INSTALL_GTEST: 1
            USE_GTEST: 1
            allow_failure: false
          - FROM:     'opensuse/leap:16.0'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-enabled-glvnd-RelWithDebInfo'
            INSTALL_GTEST: 1
            USE_GTEST: 1
            allow_failure: false
          - FROM:     'rockylinux/rockylinux:10.1'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-enabled-glvnd-RelWithDebInfo'
            INSTALL_GTEST: 1
            USE_GTEST: 1
            allow_failure: false
          - FROM:     'rockylinux/rockylinux:10.0'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-enabled-glvnd-RelWithDebInfo'
            INSTALL_GTEST: 1
            USE_GTEST: 1
            allow_failure: false

    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
          submodules: false

      # Ensure PRs are built against the PR Head
      # As opposed to the merge commit
      - name: Move to PR HEAD
        run: git checkout ${{ github.event.pull_request.head.sha }}

      - name: Extract short SHA
        shell: bash
        run: |
          echo "SHORT_SHA=`git rev-parse --short ${{ github.event.pull_request.head.sha }}`" >> $GITHUB_ENV
      - name: Test short SHA
        run: |
          echo "${SHORT_SHA}"

      - name: Build and Test
        env:
          FROM:       ${{ matrix.FROM }}
          COMPILER:   ${{ matrix.COMPILER }}
          INSTALL_GTEST: ${{ matrix.INSTALL_GTEST }}
          USE_GTEST: ${{ matrix.USE_GTEST }}
          IS_RELEASE: 0
        run: script/cibuild --preset-name="${{ matrix.preset-name }}"

      - name: Upload test results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: test_results_xml
          path: ${{github.workspace}}/test-results/**/*.xml
