name: Windows-Release
permissions:
  contents: write
  pull-requests: read

on:
  release:
    types:
      - created
      - edited
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os:              windows-2022
            triplet:         x64-win10
            preset-name:     VS2022Win64-pie-enabled-RelWithDebInfo
            python-version:  3.13.12
            is-release:      1
          - os:              windows-2025
            triplet:         x64-win10
            preset-name:     VS2022Win64-pie-enabled-RelWithDebInfo
            python-version:  3.13.12
            is-release:      1
          - os:              windows-2025-vs2026
            triplet:         x64-win10
            preset-name:     VS2026Win64-pie-enabled-RelWithDebInfo
            python-version:  3.13.12
            is-release:      1

    env:
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg
      VCPKG_ASSET_SOURCES: ${{ github.workspace }}\vcpkgAssets
      X_VCPKG_ASSET_SOURCES: clear;x-azurl,file:///${{ github.workspace }}\vcpkgAssets,,readwrite
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}\vcpkgBin,readwrite
      VCPKG_BUILD_TREES: ${{ github.workspace }}\vcpkgBuild
      VCPKG_INSTALL_OPTIONS: "--x-buildtrees-root=${{ github.workspace }}\\vcpkgBuild"
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.triplet }}
      VCPKG_OVERLAY_PORTS: ${{ github.workspace }}\custom-triplets
      PYTHONHOME: ""
      PYTHONPATH: ""
      INSTALL_GTEST: 0
      USE_GTEST: 0

    steps:
      # Process the `github.sha` value to produce the SHORT_SHA we'll need later
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 #v9.0.0
        with:
          script: |
            const git_sha = context.sha.substring(0, 7)
            core.exportVariable('SHORT_SHA', git_sha);

      - name: Test tag name and short SHA
        run: |
          echo "${TAG_NAME}"
          echo "${SHORT_SHA}"

      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
          submodules: false

      - name: Restore vcpkg cache
        id: cache-vcpkg-restore
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ${{ github.workspace }}\vcpkgAssets
            ${{ github.workspace }}\vcpkgBCache
            ${{ github.workspace }}\vcpkgBin
            ${{ github.workspace }}\vcpkgBuild
          key: vcpkgCache-${{ github.repository_owner }}-${{ matrix.os }}-${{ matrix.triplet }}-${{ hashFiles('vcpkg.json') }}

      - name: Create directories on cache miss
        run: |
          mkdir -p ${{ github.workspace }}\vcpkgAssets
          mkdir -p ${{ github.workspace }}\vcpkgBCache
          mkdir -p ${{ github.workspace }}\vcpkgBin
          mkdir -p ${{ github.workspace }}\vcpkgBuild
        if: steps.cache-vcpkg-restore.outputs.cache-hit != 'true'

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        id: vega-py-setup
        with:
          python-version: ${{ matrix.python-version }}
          update-environment: false

      - name: Install CMake
        uses: lukka/get-cmake@7bfc9baacbbdcb5e37957ad05c3546b3e222be3c # v4.3.2

      - name: Install vcpkg
        uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2 # v11.6
        with:
          binaryCachePath: "${{ github.workspace }}/vcpkgBCache"

      - name: Build the code
        run: |
          & "${{ github.workspace }}\\script\\build.ps1" -PresetName "${{ matrix.preset-name }}"
        shell: pwsh
        env:
          Python3_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          Python_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          pythonLocation: ${{ steps.vega-py-setup.outputs.python-path }}

      - name: Package the code
        run: |
          & "${{ github.workspace }}\\script\\package.ps1" -PresetName "${{ matrix.preset-name }}"
        shell: pwsh
        env:
          Python3_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          Python_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          pythonLocation: ${{ steps.vega-py-setup.outputs.python-path }}

      - name: Save vcpkg cache
        id: cache-vcpkg-save
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ${{ github.workspace }}\vcpkgAssets
            ${{ github.workspace }}\vcpkgBCache
            ${{ github.workspace }}\vcpkgBin
            ${{ github.workspace }}\vcpkgBuild
          key: ${{ steps.cache-vcpkg-restore.outputs.cache-primary-key }}
        if: steps.cache-vcpkg-restore.outputs.cache-hit != 'true'

      - name: Upload the artifacts
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "packages/*.*"
