name: Windows-Release
permissions:
  contents: write
  pull-requests: read

on:
  release:
    types:
      - created
      - edited
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os:              windows-2022
            triplet:         x64-win10
            preset-name:     VS2022Win64-pie-enabled-RelWithDebInfo
            python-version:  3.13.12
            is-release:      1
          - os:              windows-2025
            triplet:         x64-win10
            preset-name:     VS2022Win64-pie-enabled-RelWithDebInfo
            python-version:  3.13.12
            is-release:      1
          - os:              windows-2025-vs2026
            triplet:         x64-win10
            preset-name:     VS2026Win64-pie-enabled-RelWithDebInfo
            python-version:  3.13.12
            is-release:      1

    env:
      VCPKG_ROOT: ${{ github.workspace }}\\v
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.triplet }}
      VCPKG_OVERLAY_PORTS: ${{ github.workspace }}\\custom-triplets
      PYTHONHOME: ""
      PYTHONPATH: ""
      INSTALL_GTEST: 1
      USE_GTEST: 1
      INSTALL_SDL3: 0
      INSTALL_SDL3_IMAGE: 0

    steps:
      # Process the `github.sha` value to produce the SHORT_SHA we'll need later
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 #v9.0.0
        with:
          script: |
            const git_sha = context.sha.substring(0, 7)
            core.exportVariable('SHORT_SHA', git_sha);

      - name: Test tag name and short SHA
        run: |
          echo "${TAG_NAME}"
          echo "${SHORT_SHA}"

      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
          submodules: false

      - name: Restore vcpkg cache
        id: cache-vcpkg-restore
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg_cache-${{ github.repository_owner }}-${{ matrix.os }}-${{ matrix.triplet }}-${{ hashFiles('vcpkg.json') }}

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        id: vega-py-setup
        with:
          python-version: ${{ matrix.python-version }}
          update-environment: false

      - name: Install CMake
        uses: lukka/get-cmake@ea83089aa35e08e459464341fe24ad024ee2466f # v4.3.1

      - name: Install vcpkg
        uses: lukka/run-vcpkg@08ab0cc59d3f33647c5dc2b1e8f2093266c7b873

      - name: Build the code
        run: |
          & "${{ github.workspace }}\\script\\build.ps1" -PresetName "${{ matrix.preset-name }}"
        shell: pwsh
        env:
          Python3_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          Python_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          pythonLocation: ${{ steps.vega-py-setup.outputs.python-path }}

      - name: Package the code
        run: |
          & "${{ github.workspace }}\\script\\package.ps1" -PresetName "${{ matrix.preset-name }}"
        shell: pwsh
        env:
          Python3_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          Python_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          pythonLocation: ${{ steps.vega-py-setup.outputs.python-path }}

      - name: Save vcpkg cache
        id: cache-vcpkg-save
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: ${{ steps.cache-vcpkg-restore.outputs.cache-primary-key }}
        if: steps.cache-vcpkg-restore.outputs.cache-hit != 'true'

      - name: Upload the artifacts
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "packages/*.*"
