##
# Windows-Release.yml
#
# Vega Strike - Space Simulation, Combat and Trading
# Copyright (C) 2001-2026 The Vega Strike Contributors:
# Project creator: Daniel Horn
# Original development team: As listed in the AUTHORS file
# Current development team: Roy Falk, Benjamen R. Meyer, Stephen G. Tuggy
#
# https://github.com/vegastrike/Vega-Strike-Engine-Source
#
# This file is part of Vega Strike.
#
# Vega Strike is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Vega Strike is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Vega Strike.  If not, see <https://www.gnu.org/licenses/>.
#


name: Windows-Release
permissions:
  contents: write
  pull-requests: read
  packages: write

# Controls when the action will run.
on:
  release:
    types:
      - created
      - edited

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os:              windows-2022
            triplet:         x64-win10
            preset-name:     VS2022Win64-pie-enabled-RelWithDebInfo
            python-version:  3.13.12
            is-release:      1
          - os:              windows-2025
            triplet:         x64-win10
            preset-name:     VS2022Win64-pie-enabled-RelWithDebInfo
            python-version:  3.13.12
            is-release:      1
          - os:              windows-2025-vs2026
            triplet:         x64-win10
            preset-name:     VS2026Win64-pie-enabled-RelWithDebInfo
            python-version:  3.13.12
            is-release:      1

    env:
      VCPKG_ROOT: ${{ github.workspace }}/v
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.triplet }}
      VCPKG_BINARY_SOURCES: 'clear;nuget,https://nuget.pkg.github.com/stephengtuggy/index.json,readwrite'
      VCPKG_OVERLAY_PORTS: ${{ github.workspace }}/custom-triplets
      GH_PKG_REGISTRY_TOKEN: ${{ secrets.GH_PKG_REGISTRY_RW_TOKEN }}
      NUGET_AUTH_TOKEN: ${{ secrets.GH_PKG_REGISTRY_RW_TOKEN }}

    steps:
      # Process the `github.sha` value to produce the SHORT_SHA we'll need later
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd #v8.0.0
        with:
          script: |
            const git_sha = context.sha.substring(0, 7)
            core.exportVariable('SHORT_SHA', git_sha);

      - name: Test tag name and short SHA
        run: |
          echo "${TAG_NAME}"
          echo "${SHORT_SHA}"

        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        id: vega-py-setup
        with:
          python-version: ${{ matrix.python-version }}
          update-environment: false

      - name: install-cmake
        uses: lukka/get-cmake@b78306120111dc2522750771cfd09ee7ca723687 # v4.3.0

      - name: Get CPU count
        run: |
          [Int32]$MAX_THREADS_TO_BUILD_WITH=4
          [Int32]$num_threads_to_build_with=[Int32]::Parse($env:NUMBER_OF_PROCESSORS)
          echo "Number of threads to build with before capping: $num_threads_to_build_with"
          $num_threads_to_build_with=[Int32]::Min($num_threads_to_build_with, $MAX_THREADS_TO_BUILD_WITH)
          echo "Number of threads to build with after capping: $num_threads_to_build_with"
          echo "THREADS_TO_BUILD_WITH=$num_threads_to_build_with" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: run-vcpkg
        uses: lukka/run-vcpkg@5e0cab206a5ea620130caf672fce3e4a6b5666a1 # v11.5
        with:
          vcpkgDirectory: ${{ env.VCPKG_ROOT }}
        env:
          Python3_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          Python_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          pythonLocation: ${{ steps.vega-py-setup.outputs.python-path }}
          PYTHONHOME: ""
          PYTHONPATH: ""

      - name: Set up NuGet Credentials
        shell: pwsh
        env:
          NuGetPackageSourceCredentials_GitHub: "UserName=stephengtuggy;Password=$GH_PKG_REGISTRY_TOKEN"
        run: |
          & $(& $Env:VCPKG_ROOT/vcpkg.exe fetch nuget | select -last 1) sources add `
            -Source https://nuget.pkg.github.com/stephengtuggy/index.json `
            -Name GitHub
          & $(& $Env:VCPKG_ROOT/vcpkg.exe fetch nuget | select -last 1) setapikey "$GH_PKG_REGISTRY_TOKEN" `
            -Source https://nuget.pkg.github.com/stephengtuggy/index.json

      - name: run-cmake
        uses: lukka/run-cmake@af1be47fd7c933593f687731bc6fdbee024d3ff4 # v10.8
        env:
          Python3_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          Python_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          pythonLocation: ${{ steps.vega-py-setup.outputs.python-path }}
          PYTHONHOME: ""
          PYTHONPATH: ""
          INSTALL_GTEST: 0
          USE_GTEST: 0
          INSTALL_SDL3: 0
          INSTALL_SDL3_IMAGE: 0
        with:
          configurePreset: ${{ matrix.preset-name }}
          buildPreset: "build-${{ matrix.preset-name }}"
          buildPresetAdditionalArgs: "['/p:CL_MPcount=$THREADS_TO_BUILD_WITH']"
          packagePreset: "package-${{ matrix.preset-name }}"

      - name: Upload the artifacts
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "packages/*.*"
